### ISSUE TITLE
No such file or directory：tinyimagenet_200.txt 

### ISSUE THREAD

**Issue by zstarN70** [OatmealLiu/class-iNCD#1]
Please tell me how to obtain the file? Or what format the file was generated from?

**Comment by roysubhankar** [comment]
Hi,

Did you follow the instructions for preparing the tinyimagenet dataset as described in our repo?

> For TinyImagenet, to download and generate image folders to ./data/datasets/. Please follow https://github.com/tjmoon0104/pytorch-tiny-imagenet

**Comment by zhunzhong07** [comment]
@zstarN70 Hi, thanks for your interest in our work.

If you extract the tiny-imagenet file, you can obtain the file **wnids.txt**. Please rename it to **tinyimagenet_200.txt**.

Sorry for this confusion.

We will update a more detailed instruction of preparing datasets. @OatmealLiu

**Comment by OatmealLiu** [comment]
@zstarN70 Hi! Thanks for running our code.

I uploaded the prepared datasets (CIFAR-10, CIFAR-100 and TinyImagenet) to drive. You can now download the dataset from: https://drive.google.com/file/d/1o73ehAii6AJpJQ5tMwfywE2JBiFC3Bv7/view?usp=sharing

After you downloaded it, you can move the downloaded `datasets.zip` file to `./data/` folder. Then you can unzip `datasets.zip` to `./data/` folder.

I also updated the dataset preparation instruction in our README.md file. You can also check it there.

Thanks!

Best regards,
Miu

**Comment by zstarN70** [comment]
@OatmealLiu @zhunzhong07 Thank you for your reply！Excellent work！
