### ISSUE TITLE
Unable to download the datasets

### ISSUE THREAD

**Issue by Asadmeinyoureyes** [OatmealLiu/class-iNCD#11]
Sorry to bother you, but the data set seems to be unable to be downloaded. Could you please update the download path of the datasets?

**Comment by OatmealLiu** [comment]
Hi! Thank you for pointing out the invalid link. Just found the drive folder was erased due university drive policy updates. 

I uploaded the sets again and updated the link. You can download from here: https://drive.google.com/file/d/1O0PPC_Bk16XLLe-UFCSw1UdbRSc-DyOI/view?usp=sharing

**Comment by Asadmeinyoureyes** [comment]
@OatmealLiu thank you!
