### ISSUE TITLE
Qusetion about the unlabeled classifier

### ISSUE THREAD

**Issue by jumptiger66** [OatmealLiu/class-iNCD#7]
It seems that i must know the noval class number before stage 2 , because i need to set a classifier with fixed output dimensions for Eq 4.

**Comment by OatmealLiu** [comment]
Hi! Thanks for being interested in our work!

Yes, in NCD, the number of novel class discovery is known as a-priori. In our work class-iNCD, we focus on tackling the class-incremental NCD setting, mitigating the forgetting issue when an algorithm doing NCD incrementally. 

GCD (Generalized Category Discovery) related works are trying to tackle NCD problem without this assumption. If you need, GCD works might help you.

Thanks!
Miu

**Comment by jumptiger66** [comment]
Thank u for your reply . Have a good day .
